name: Fetch Daily Markets

on:
  schedule:
    # 每天 UTC 23:05 跑一次（洛杉矶时间大约下午/傍晚，按需调整）
    - cron: "5 23 * * *"
  workflow_dispatch: {}     # 允许手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入内容（用于 git push）
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetcher
        env:
          GOOGLE_SHEETS_CREDENTIALS_JSON: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_JSON }}
          GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
        run: |
          python fetch_markets.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.csv data/history.csv || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update market snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi

